# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Create packages directory
        run: mkdir packages
      - name: Create bin directory
        run: mkdir -p mikecore/bin
      - uses: actions/checkout@v2
      - name: Get nuget packages
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: ls -l
      - name: Install nuget packages
        run: |
          nuget install DHI.MikeCore.Linux.rhel7 -Version 19.0.0 -OutputDirectory packages
      - run: cp -r packages/DHI.MikeCore.Linux.rhel7.19.0.0/runtimes/linux-x64/native/* mikecore/bin/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with: 
          name: bin
          path: bin
